config/routes.rb
Rails.application.routes.draw do

  root 'people#index'

  resources :people

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def show
      @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      redirect_to people_path
    else
      render :new
    end
  end

  def edit
  end

  private

  def person_params
    params.require(:person).permit(:name, :age, :race, :hair_color)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/_navbar.html.erb
<ul id="dropdown1" class="dropdown-content">
  <li><a href="#!">one</a></li>
  <li><a href="#!">two</a></li>
  <li class="divider"></li>
  <li><a href="#!">three</a></li>
</ul>
<nav>
  <div class="nav-wrapper">
    <a href="#!" class="brand-logo">Logo</a>
    <ul class="right hide-on-med-and-down">
      <li><a href="sass.html">Sass</a></li>
      <li><a href="badges.html">Components</a></li>
      <li><a class="dropdown-button" href="#!" data-activates="dropdown1">Dropdown<i class="material-icons right">arrow_drop_down</i></a></li>
    </ul>
  </div>
</nav>
<nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MaterializePrac</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/edit.html.erb
<ul id="dropdown1" class="dropdown-content">
  <li><a href="#!">one</a></li>
  <li><a href="#!">two</a></li>
  <li class="divider"></li>
  <li><a href="#!">three</a></li>
</ul>
<nav>
  <div class="nav-wrapper">
    <a href="#!" class="brand-logo">Logo</a>
    <ul class="right hide-on-med-and-down">
      <li><a href="sass.html">Sass</a></li>
      <li><a href="badges.html">Components</a></li>
      <li><a class="dropdown-button" href="#!" data-activates="dropdown1">Dropdown<i class="material-icons right">arrow_drop_down</i></a></li>
    </ul>
  </div>
</nav>

<h1>People#edit</h1>
<p>Find me in app/views/people/edit.html.erb</p>

app/views/people/index.html.erb
<ul id="dropdown1" class="dropdown-content">
  <li> <%= link_to 'New Entry', new_person_path %> </li>
  <li><a href="http://localhost:3000/people/new">Same place, different style</a></li>
  <li class="divider"></li>
  <li><a href="#!">three</a></li>
</ul>
<nav>
  <div class="nav-wrapper" "color-red">
    <a href="#!" class="brand-logo">Logo</a>
    <ul class="right hide-on-med-and-down">
      <li><a href="sass.html">Sass</a></li>
      <li><a href="badges.html">Components</a></li>
      <li><a class="dropdown-button" href="#!" data-activates="dropdown1">Dropdown<i class="material-icons right">arrow_drop_down</i></a></li>
    </ul>
  </div>
</nav>
,



<h3> People </h3>

  <% if @people.any? %>
      <% @people.each do |person| %>
        <div>
          <%= person.name %>
          <%= person.age %>
          <%= person.race %>
          <%= person.hair_color %>
          <%= link_to 'Show page', person_path(person) %>
        </div>
      <% end %>

    <% else %>
      <h3> No people found. Make an entry </h3>
    <% end %>

    <hr />
    <%= link_to 'New person', new_person_path %>

app/views/people/new.html.erb
<ul id="dropdown1" class="dropdown-content">
  <li><a href="#!">one</a></li>
  <li><a href="#!">two</a></li>
  <li class="divider"></li>
  <li><a href="#!">three</a></li>
</ul>
<nav>
  <h3>New Person</h3>
  <div class="nav-wrapper">
    <a href="#!" class="brand-logo">Logo</a>
    <ul class="right hide-on-med-and-down">
      <li><a href="sass.html">S</a></li>
      <li><a href="badges.html">Components</a></li>
      <li><a class="dropdown-button" href="#!" data-activates="dropdown1">Dropdown<i class="material-icons right">arrow_drop_down</i></a></li>
    </ul>
  </div>
</nav>
<h2 class="body">New person</h2>

  <%= form_for @person do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :age %>
      <%= f.number_field :age %>

      <%= f.label :hair_color %>
      <%= f.text_field :hair_color %>

      <%= f.label :race %>
      <%= f.text_field :race %>

    <%= f.submit %>
  <% end %>

app/views/people/show.html.erb
<ul id="dropdown1" class="dropdown-content">
  <li><a href="#!">one</a></li>
  <li><a href="#!">two</a></li>
  <li class="divider"></li>
  <li><a href="#!">three</a></li>
</ul>
<nav>
  <div class="nav-wrapper">
    <a href="#!" class="brand-logo">Logo</a>
    <ul class="right hide-on-med-and-down">
      <li><a href="sass.html">Sass</a></li>
      <li><a href="badges.html">Components</a></li>
      <li><a class="dropdown-button"
        href="#!" data-activates="dropdown1">Dropdown
        <i class="material-icons right">arrow_drop_down</i></a>
      </li>
    </ul>
  </div>
</nav>

<h3> Show person </h3>
  <h2><%= @person.name %></h2>
  <h2><%= @person.age %> </h2>
  <h2><%= @person.race %> </h2>
  <h2><%= @person.hair_color %></h2>
  <%= link_to 'Back', people_path %>